set_property IOSTANDARD LVCMOS33 [get_ports btnc]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports hsync]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaBlue[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaBlue[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaBlue[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaBlue[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaGreen[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaGreen[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaGreen[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaGreen[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaRed[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaRed[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaRed[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaRed[0]}]
set_property PACKAGE_PIN N18 [get_ports {vgaBlue[0]}]
set_property PACKAGE_PIN L18 [get_ports {vgaBlue[1]}]
set_property PACKAGE_PIN K18 [get_ports {vgaBlue[2]}]
set_property PACKAGE_PIN J18 [get_ports {vgaBlue[3]}]
set_property PACKAGE_PIN J17 [get_ports {vgaGreen[0]}]
set_property PACKAGE_PIN H17 [get_ports {vgaGreen[1]}]
set_property PACKAGE_PIN G17 [get_ports {vgaGreen[2]}]
set_property PACKAGE_PIN D17 [get_ports {vgaGreen[3]}]
set_property PACKAGE_PIN G19 [get_ports {vgaRed[0]}]
set_property PACKAGE_PIN H19 [get_ports {vgaRed[1]}]
set_property PACKAGE_PIN J19 [get_ports {vgaRed[2]}]
set_property PACKAGE_PIN N19 [get_ports {vgaRed[3]}]
set_property PACKAGE_PIN P19 [get_ports hsync]
set_property PACKAGE_PIN R19 [get_ports vsync]
set_property PACKAGE_PIN U18 [get_ports btnc]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN R2 [get_ports rst]

set_property IOSTANDARD LVCMOS33 [get_ports up]
set_property PACKAGE_PIN T18 [get_ports up]
set_property IOSTANDARD LVCMOS33 [get_ports down]
set_property PACKAGE_PIN U17 [get_ports down]
set_property IOSTANDARD LVCMOS33 [get_ports left]
set_property PACKAGE_PIN W19 [get_ports left]
set_property IOSTANDARD LVCMOS33 [get_ports right]
set_property PACKAGE_PIN T17 [get_ports right]

set_property IOSTANDARD LVCMOS33 [get_ports {SSD[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSD[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSD[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSD[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSD[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSD[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSD[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSD[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSD_sel[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSD_sel[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSD_sel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSD_sel[0]}]
set_property PACKAGE_PIN W7 [get_ports {SSD[7]}]
set_property PACKAGE_PIN W6 [get_ports {SSD[6]}]
set_property PACKAGE_PIN U8 [get_ports {SSD[5]}]
set_property PACKAGE_PIN V8 [get_ports {SSD[4]}]
set_property PACKAGE_PIN U5 [get_ports {SSD[3]}]
set_property PACKAGE_PIN V5 [get_ports {SSD[2]}]
set_property PACKAGE_PIN U7 [get_ports {SSD[1]}]
set_property PACKAGE_PIN V7 [get_ports {SSD[0]}]
set_property PACKAGE_PIN W4 [get_ports {SSD_sel[3]}]
set_property PACKAGE_PIN V4 [get_ports {SSD_sel[2]}]
set_property PACKAGE_PIN U4 [get_ports {SSD_sel[1]}]
set_property PACKAGE_PIN U2 [get_ports {SSD_sel[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports audio_lrck]
set_property IOSTANDARD LVCMOS33 [get_ports audio_mclk]
set_property IOSTANDARD LVCMOS33 [get_ports audio_sck]
set_property IOSTANDARD LVCMOS33 [get_ports audio_sdin]
set_property PACKAGE_PIN A14 [get_ports audio_mclk]
set_property PACKAGE_PIN A16 [get_ports audio_lrck]
set_property PACKAGE_PIN B15 [get_ports audio_sck]
set_property PACKAGE_PIN B16 [get_ports audio_sdin]

set_property IOSTANDARD LVCMOS33 [get_ports {LED[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}]
set_property PACKAGE_PIN L1 [get_ports {LED[15]}]
set_property PACKAGE_PIN P1 [get_ports {LED[14]}]
set_property PACKAGE_PIN N3 [get_ports {LED[13]}]
set_property PACKAGE_PIN P3 [get_ports {LED[12]}]
set_property PACKAGE_PIN U3 [get_ports {LED[11]}]
set_property PACKAGE_PIN W3 [get_ports {LED[10]}]
set_property PACKAGE_PIN V3 [get_ports {LED[9]}]
set_property PACKAGE_PIN V13 [get_ports {LED[8]}]
set_property PACKAGE_PIN V14 [get_ports {LED[7]}]
set_property PACKAGE_PIN U14 [get_ports {LED[6]}]
set_property PACKAGE_PIN U15 [get_ports {LED[5]}]
set_property PACKAGE_PIN W18 [get_ports {LED[4]}]
set_property PACKAGE_PIN V19 [get_ports {LED[3]}]
set_property PACKAGE_PIN U19 [get_ports {LED[2]}]
set_property PACKAGE_PIN E19 [get_ports {LED[1]}]
set_property PACKAGE_PIN U16 [get_ports {LED[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports PS2_DATA]
set_property PACKAGE_PIN B17 [get_ports PS2_DATA]
set_property IOSTANDARD LVCMOS33 [get_ports PS2_CLK]
set_property PACKAGE_PIN C17 [get_ports PS2_CLK]

#set_property IOSTANDARD LVCMOS33 [get_ports down_online]
#set_property PACKAGE_PIN N2 [get_ports down_online]

set_property IOSTANDARD LVCMOS33 [get_ports up_online]
set_property PACKAGE_PIN K17 [get_ports up_online]
set_property IOSTANDARD LVCMOS33 [get_ports right_online]
set_property PACKAGE_PIN M18 [get_ports down_online]
set_property IOSTANDARD LVCMOS33 [get_ports down_online]
set_property IOSTANDARD LVCMOS33 [get_ports left_online]
set_property PACKAGE_PIN N17 [get_ports left_online]
set_property PACKAGE_PIN P18 [get_ports right_online]

set_property PULLDOWN true [get_ports left_online]
set_property PULLDOWN true [get_ports down_online]
set_property PULLDOWN true [get_ports up_online]
set_property PULLDOWN true [get_ports right_online]

set_property PACKAGE_PIN J3 [get_ports {vauxp6}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vauxp6}]
#Sch name = XA2_P
set_property PACKAGE_PIN L3 [get_ports {vauxp14}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vauxp14}]
#Sch name = XA3_P
set_property PACKAGE_PIN M2 [get_ports {vauxp7}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vauxp7}]
#Sch name = XA4_P
set_property PACKAGE_PIN N2 [get_ports {vauxp15}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vauxp15}]
#Sch name = XA1_N
set_property PACKAGE_PIN K3 [get_ports {vauxn6}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vauxn6}]
#Sch name = XA2_N
set_property PACKAGE_PIN M3 [get_ports {vauxn14}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vauxn14}]
#Sch name = XA3_N
set_property PACKAGE_PIN M1 [get_ports {vauxn7}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vauxn7}]
#Sch name = XA4_N
set_property PACKAGE_PIN N1 [get_ports {vauxn15}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {vauxn15}]

# Switches
set_property PACKAGE_PIN V17 [get_ports {sw[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw[0]}]
set_property PACKAGE_PIN V16 [get_ports {sw[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {sw[1]}]
